#kind: Pod
#apiVersion: v1
#metadata:
#  name: sample1
#spec:
#  containers:
#    - name: nginx
#      image: nginx
#
#---
#kind: Pod
#apiVersion: v1
#metadata:
#  name: sample2
#spec:
#  containers:
#    - name: nginx
#      image: nginx
#    - name: mongodb
#      image: mongo
#
#---
kind: Pod
apiVersion: v1
metadata:
  name: sample3
spec:
  containers:
    - name: nginx
      image: nginx
    - name: centos
      image: centos:7
      command: ["sleep", "1000000"]
