#kind: Pod
#apiVersion: v1
#metadata:
#  name: sample1
#spec:
#  containers:
#    - name: nginx
#      image: nginx
#
#---
#kind: Pod
#apiVersion: v1
#metadata:
#  name: sample2
#spec:
#  containers:
#    - name: nginx
#      image: nginx
#    - name: mongodb
#      image: mongo
#
#---
kind: Pod
apiVersion: v1
metadata:
  name: sample3
spec:
  containers:
    - name: nginx
      image: nginx
    - name: centos
      image: centos:7
      command: ["sleep", "1000"]

---

kind: Pod
apiVersion: v1
metadata:
  name: sample4
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["sleep", "1000"]
      env:
        - name: URL
          value: example.com

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap1
data:
  URL: example.com
  SUBDOMAIN: sample
  FULL_URL: sample.example.com

---
kind: Pod
apiVersion: v1
metadata:
  name: sample6
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["sleep", "1000"]
      envFrom:
       - configMapRef:
           name: configmap1

---
kind: Secret
apiVersion: v1
metadata:
  name: secret1
data:
  dbusername: bW9u
  dbpassword: c2FsaW5pMTIz

---

kind: Pod
apiVersion: v1
metadata:
  name: sample7
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["sleep", "1000"]
      envFrom:
        - secretRef:
            name: secret1

---
apiVersion: v1
kind: Pod
metadata:
  name: sample10
spec:
  containers:
    - name: liveness
      image: k8s.gcr.io/busybox
      args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5