apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend-rs
  template:
    metadata:
      labels:
        tier: frontend-rs
    spec:
     containers:
      - name: nginx
        image: nginx:1.16
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend-deploy
  template:
    metadata:
      labels:
        tier: frontend-deploy
    spec:
      containers:
        - name: nginx
          image: nginx:1.18